#重置（清空）k8s集群
#--------------------------------------------------------------------
- hosts: etcd
  remote_user: root
  tasks:
  - name: 删除容器
    tags: reset,reset-etcd
    shell: "docker rm -vf etcd"
    ignore_errors: yes
  - name: 删除目录
    tags: reset,reset-etcd
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /etc/kubernetes
    - /tmp/etcd
    - /var/lib/etcd
- hosts: node,master
  remote_user: root
  tasks:
  - name: reset cluster
    tags: reset,reset-k8s
    shell: kubeadm reset -f
  - name: reset iptables
    tags: reset,reset-k8s
    shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
  - name: reset cni0
    tags: reset,reset-k8s
    shell: ip link del cni0
    ignore_errors: yes
  - name: reset flannel.1
    tags: reset,reset-k8s
    shell: ip link del flannel.1
    ignore_errors: yes
  - name: reset restart docker
    tags: reset,restart-docker
    shell: systemctl restart docker

#彻底清理docker与k8s
#--------------------------------------------------------------------
- hosts: node,master
  remote_user: root
  tasks:
  - name: stop docker
    tags: clear,stop-docker
    shell: systemctl stop docker
  - name: remove softs
    tags: clear,remove
    shell: yum -y remove docker* kube*
  - name: reboot
    tags: clear,remove
    shell: reboot
  - name: reboot sleep
    tags: clear,remove
    shell: sleep 60
  - name: reboot clear docker
    tags: clear,remove
    shell: "rm -rf /etc/systemd/system/docker.service \
            /etc/systemd/system/docker.service.d \
            /var/lib/docker \
            /var/run/docker"
  - name: reboot clear k8s
    tags: clear,remove
    shell: "for path in $(find / -name kube*); do rm -rf $path; done"
